"use client";

import Link from "next/link";
import { useState, useEffect, useMemo, useCallback, useRef } from "react";
import { RefreshCwIcon, CalendarIcon } from "lucide-react";

import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import { format } from "date-fns";
import { generateContractCode } from "@/app/(app)/app/access-management/contract-actions";
import { RichTextEditor } from "./rich-text-editor";

type ContractFormProps = {
  action: (formData: FormData) => Promise<void>;
  clients: Array<{ id: number; company_name: string; client_code: string }>;
  mode: "create" | "edit";
  values?: {
    client_id?: number;
    contract_number?: string;
    contract_title?: string;
    project_name?: string;
    contract_date?: string;
    start_date?: string;
    end_date?: string;
    contract_value?: string | number;
    project_scope?: string;
    payment_scheme_summary?: string | null;
    contract_status?: string;
    notes?: string | null;
  };
};

const statusOptions = [
  ["draft", "Draft"],
  ["active", "Aktif"],
  ["completed", "Selesai"],
  ["terminated", "Dihentikan"],
  ["expired", "Kedaluwarsa"],
  ["cancelled", "Dibatalkan"],
] as const;

function DatePicker({
  id,
  label,
  value,
  required,
  disabledBefore,
  disabledAfter,
  onChange,
}: {
  id: string;
  label: string;
  value?: string;
  required?: boolean;
  disabledBefore?: Date;
  disabledAfter?: Date;
  onChange?: (date: Date | undefined) => void;
}) {
  const [open, setOpen] = useState(false);
  const date = useMemo(() => (value ? new Date(value) : undefined), [value]);
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(date);

  const handleSelect = (newDate: Date | undefined) => {
    setSelectedDate(newDate);
    if (newDate) {
      setOpen(false);
      const input = document.getElementById(id) as HTMLInputElement;
      if (input) {
        input.value = format(newDate, "yyyy-MM-dd");
      }
      onChange?.(newDate);
    }
  };

  // Sync selectedDate when date prop changes
  useEffect(() => {
    setSelectedDate(date);
  }, [date]);

  return (
    <Field>
      <FieldLabel htmlFor={id}>{label}</FieldLabel>
      <Popover open={open} onOpenChange={setOpen}>
        <PopoverTrigger asChild>
          <Button
            type="button"
            variant="outline"
            role="combobox"
            aria-expanded={open}
            className="flex w-full items-center justify-between rounded-2xl border border-input bg-background px-3 py-2 text-sm hover:bg-muted/50"
          >
            <span className={cn(!selectedDate && "text-muted-foreground")}>
              {selectedDate ? format(selectedDate, "PPP") : "Pilih tanggal"}
            </span>
            <CalendarIcon className="h-4 w-4 opacity-50" />
          </Button>
        </PopoverTrigger>
        <PopoverContent className="w-auto p-0" align="start">
          <Calendar
            mode="single"
            selected={selectedDate}
            onSelect={handleSelect}
            disabled={(d) => {
              if (disabledBefore && d < disabledBefore) return true;
              if (disabledAfter && d <= disabledAfter) return true;
              return false;
            }}
            initialFocus
          />
        </PopoverContent>
      </Popover>
      <input
        type="hidden"
        id={id}
        name={id.replace(/-/g, "_")}
        defaultValue={value}
        required={required}
      />
    </Field>
  );
}

export function ContractForm({ action, clients, mode, values }: ContractFormProps) {
  const isCreate = mode === "create";
  const [contractNumber, setContractNumber] = useState(values?.contract_number ?? "");
  const [isGeneratingNumber, setIsGeneratingNumber] = useState(false);
  const [startDate, setStartDate] = useState<Date | undefined>(
    values?.start_date ? new Date(values.start_date) : undefined
  );
  const hasAutoGenerated = useRef(false);

  const today = useMemo(() => {
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    return d;
  }, []);

  const availableStatusOptions = isCreate
    ? statusOptions.filter(([value]) => value === "draft" || value === "active")
    : statusOptions;

  const handleGenerateNumber = useCallback(async () => {
    setIsGeneratingNumber(true);
    try {
      const code = await generateContractCode();
      setContractNumber((prev) => prev || code);
    } catch (error) {
      console.error("Failed to generate contract number:", error);
    } finally {
      setIsGeneratingNumber(false);
    }
  }, []);

  useEffect(() => {
    if (isCreate && !contractNumber && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerateNumber();
    }
  }, [isCreate]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <Card>
      <CardHeader className="gap-3">
        <CardTitle>{isCreate ? "Tambah kontrak baru" : "Perbarui data kontrak"}</CardTitle>
        <CardDescription>
          Susun identitas kontrak, proyek, dan status operasional dalam satu form yang langsung terhubung ke API backend.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form action={action} className="flex flex-col gap-7">
          <FieldGroup>
            <Field>
              <FieldLabel htmlFor="client_id">Klien</FieldLabel>
              <Select
                name="client_id"
                defaultValue={values?.client_id ? String(values.client_id) : ""}
                required
              >
                <SelectTrigger
                  data-testid="contract-form-client"
                  id="client_id"
                  className="w-full"
                >
                  <SelectValue placeholder="Pilih klien" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {clients.map((client) => (
                      <SelectItem key={client.id} value={String(client.id)}>
                        {client.client_code} — {client.company_name}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>

            <Field>
              <FieldLabel htmlFor="contract_number">Nomor kontrak</FieldLabel>
              <div className="flex gap-2">
                <Input
                  data-testid="contract-form-number"
                  id="contract_number"
                  name="contract_number"
                  value={contractNumber}
                  onChange={(e) => setContractNumber(e.target.value)}
                  placeholder="CSM-V-2025-0001"
                  required
                  className="flex-1"
                />
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleGenerateNumber}
                  disabled={isGeneratingNumber}
                  data-testid="contract-form-generate-number"
                >
                  <RefreshCwIcon className={cn("h-4 w-4 mr-2", isGeneratingNumber && "animate-spin")} />
                  Generate
                </Button>
              </div>
              <FieldDescription>
                Nomor kontrak akan otomatis digenerate dengan format CSM-BLN-TAHUN-NOMOR (bulan dalam Romawi).
              </FieldDescription>
            </Field>

            <Field>
              <FieldLabel htmlFor="contract_title">Judul kontrak</FieldLabel>
              <Input data-testid="contract-form-title" defaultValue={values?.contract_title ?? ""} id="contract_title" name="contract_title" required />
            </Field>

            <Field>
              <FieldLabel htmlFor="project_name">Nama proyek</FieldLabel>
              <Input data-testid="contract-form-project" defaultValue={values?.project_name ?? ""} id="project_name" name="project_name" required />
            </Field>

            <DatePicker
              id="contract_date"
              label="Tanggal kontrak"
              value={values?.contract_date}
              required
              disabledBefore={today}
            />

            <DatePicker
              id="start_date"
              label="Tanggal mulai"
              value={values?.start_date}
              required
              disabledBefore={today}
              onChange={setStartDate}
            />

            <DatePicker
              id="end_date"
              label="Tanggal selesai"
              value={values?.end_date}
              required
              disabledBefore={today}
              disabledAfter={startDate}
            />

            <Field>
              <FieldLabel htmlFor="contract_value">Nilai kontrak</FieldLabel>
              <Input data-testid="contract-form-value" defaultValue={String(values?.contract_value ?? "")} id="contract_value" name="contract_value" required type="number" />
            </Field>

            <Field>
              <FieldLabel htmlFor="contract_status">Status kontrak</FieldLabel>
              <Select
                name="contract_status"
                defaultValue={values?.contract_status ?? "draft"}
              >
                <SelectTrigger
                  data-testid="contract-form-status"
                  id="contract_status"
                  className="w-full"
                >
                  <SelectValue placeholder="Pilih status" />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {availableStatusOptions.map(([value, label]) => (
                      <SelectItem key={value} value={value}>
                        {label}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>

            <Field>
              <FieldLabel htmlFor="payment_scheme_summary">Ringkasan skema pembayaran</FieldLabel>
              <Textarea data-testid="contract-form-payment-scheme" defaultValue={values?.payment_scheme_summary ?? ""} id="payment_scheme_summary" name="payment_scheme_summary" />
            </Field>

            <Field>
              <FieldLabel>Ruang lingkup proyek</FieldLabel>
              <RichTextEditor
                content={values?.project_scope ?? ""}
                placeholder="Jelaskan ruang lingkup dan detail proyek..."
                name="project_scope"
              />
            </Field>

            <Field>
              <FieldLabel htmlFor="notes">Catatan</FieldLabel>
              <Textarea data-testid="contract-form-notes" defaultValue={values?.notes ?? ""} id="notes" name="notes" />
              <FieldDescription>Gunakan catatan untuk konteks operasional penting yang perlu terbaca cepat oleh tim.</FieldDescription>
            </Field>
          </FieldGroup>

          <div className="flex flex-wrap items-center gap-3">
            <Button data-testid="contract-form-submit" size="lg" type="submit">{isCreate ? "Simpan kontrak" : "Simpan perubahan"}</Button>
            <Link className={buttonVariants({ size: "lg", variant: "outline" })} href="/app/contracts">Batal</Link>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
